"""
Industry-Standard CI/CD Templates — v2.0
Enhanced with: security scanning, iOS builds, deployment stages,
artifact management, environment-based deployments, and monitoring.
"""

from __future__ import annotations

from pipeline.core.models import MobileFramework


# ── Shared CI Components ───────────────────────────────────────────────────

_SECURITY_SCANNING = """
# ────────────────────────────────────────────
# Security & Compliance
# ────────────────────────────────────────────
sast:
  stage: security
  image: node:20-alpine
  script:
    - npx audit-ci --moderate
    - npx eslint --ext .ts,.tsx src/ --format json --output-file gl-sast-report.json || true
  artifacts:
    reports:
      sast: gl-sast-report.json
    expire_in: 7 days
  allow_failure: true

dependency_scan:
  stage: security
  image: node:20-alpine
  script:
    - npm audit --audit-level=high --json > gl-dependency-report.json || true
  artifacts:
    reports:
      dependency_scanning: gl-dependency-report.json
    expire_in: 7 days
  allow_failure: true

secret_detection:
  stage: security
  image: alpine:latest
  script:
    - apk add --no-cache grep
    - |
      echo "Scanning for hardcoded secrets..."
      PATTERNS="sk-ant-|ghp_|glpat-|AKIA|password=|api_key=|secret="
      if grep -rn -E "$PATTERNS" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.json" . 2>/dev/null | grep -v node_modules | grep -v .env.example; then
        echo "⚠️ Potential secrets found! Review above matches."
        exit 1
      fi
      echo "✅ No hardcoded secrets detected"
  allow_failure: false
"""

_NOTIFICATION_JOB = """
notify_success:
  stage: notify
  image: alpine:latest
  script:
    - echo "✅ Pipeline passed for $CI_PROJECT_NAME"
  when: on_success
  only: [main, tags]

notify_failure:
  stage: notify
  image: alpine:latest
  script:
    - echo "❌ Pipeline FAILED for $CI_PROJECT_NAME — check logs"
  when: on_failure
  only: [main, tags]
"""


# ── Framework-Specific Templates ───────────────────────────────────────────

CI_TEMPLATES: dict[str, str] = {}

CI_TEMPLATES["expo"] = f"""\
# ============================================================================
# 📱 GitLab CI/CD — Expo / React Native (Managed Workflow)
# Generated by Repo Evolution Pipeline v2.0
# ============================================================================

image: node:20

variables:
  EXPO_NO_TELEMETRY: "1"
  CI: "true"
  NODE_OPTIONS: "--max-old-space-size=4096"

stages:
  - install
  - lint
  - test
  - security
  - build
  - deploy
  - notify

cache:
  key: "${{CI_COMMIT_REF_SLUG}}-node"
  paths:
    - node_modules/
    - .expo/
  policy: pull-push

# ────────────────────────────────────────────
# Install
# ────────────────────────────────────────────
install:
  stage: install
  script:
    - npm ci --prefer-offline --no-audit
  artifacts:
    paths: [node_modules/]
    expire_in: 1 hour

# ────────────────────────────────────────────
# Lint & Type Check
# ────────────────────────────────────────────
lint:
  stage: lint
  script:
    - npx tsc --noEmit || echo "Type errors found — review above"
    - npx eslint src/ --ext .ts,.tsx --max-warnings 10 || true
  needs: [install]

# ────────────────────────────────────────────
# Tests
# ────────────────────────────────────────────
test_unit:
  stage: test
  script:
    - npx jest --ci --coverage --passWithNoTests
  coverage: '/All files.*?\\|.*?(\\d+\\.\\d+)/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths: [coverage/]
    expire_in: 7 days
  needs: [install]

{_SECURITY_SCANNING}

# ────────────────────────────────────────────
# Build — Android
# ────────────────────────────────────────────
build_android:
  stage: build
  script:
    - npx expo export --platform android
  artifacts:
    paths: [dist/]
    expire_in: 30 days
  needs: [test_unit, lint]
  only: [main, tags]

# ────────────────────────────────────────────
# Build — Web (Preview)
# ────────────────────────────────────────────
build_web:
  stage: build
  script:
    - npx expo export --platform web
  artifacts:
    paths: [dist/]
    expire_in: 7 days
  needs: [test_unit]
  except: [tags]

# ────────────────────────────────────────────
# Deploy — EAS (Production Build & Submit)
# ────────────────────────────────────────────
deploy_eas_android:
  stage: deploy
  script:
    - npx eas-cli build --platform android --profile production --non-interactive
    - npx eas-cli submit --platform android --profile production --non-interactive
  only: [tags]
  environment:
    name: production/android

deploy_eas_ios:
  stage: deploy
  script:
    - npx eas-cli build --platform ios --profile production --non-interactive
    - npx eas-cli submit --platform ios --profile production --non-interactive
  only: [tags]
  environment:
    name: production/ios

# ────────────────────────────────────────────
# Deploy — GitLab Pages (web preview)
# ────────────────────────────────────────────
pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/* public/ 2>/dev/null || echo "No web export found"
  artifacts:
    paths: [public/]
  needs: [build_web]
  only: [main]
  environment:
    name: preview
    url: https://${{CI_PROJECT_NAMESPACE}}.gitlab.io/${{CI_PROJECT_NAME}}

{_NOTIFICATION_JOB}
"""

CI_TEMPLATES["react-native"] = f"""\
# ============================================================================
# 📱 GitLab CI/CD — React Native (Bare Workflow)
# Generated by Repo Evolution Pipeline v2.0
# ============================================================================

image: reactnativecommunity/react-native-android:v12.0

variables:
  CI: "true"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
  NODE_OPTIONS: "--max-old-space-size=4096"

stages:
  - install
  - lint
  - test
  - security
  - build_android
  - build_ios
  - deploy
  - notify

cache:
  key: "${{CI_COMMIT_REF_SLUG}}-rn"
  paths:
    - node_modules/
    - android/.gradle/
    - ~/.gradle/caches/
  policy: pull-push

install:
  stage: install
  script:
    - npm ci --legacy-peer-deps --prefer-offline --no-audit
  artifacts:
    paths: [node_modules/]
    expire_in: 1 hour

lint:
  stage: lint
  script:
    - npx tsc --noEmit
    - npx eslint src/ --ext .ts,.tsx --max-warnings 10 || true
  needs: [install]

test_unit:
  stage: test
  script:
    - npx jest --ci --coverage --passWithNoTests
  coverage: '/All files.*?\\|.*?(\\d+\\.\\d+)/'
  artifacts:
    reports:
      junit: junit.xml
    paths: [coverage/]
    expire_in: 7 days
  needs: [install]

{_SECURITY_SCANNING}

build_android_debug:
  stage: build_android
  script:
    - cd android && ./gradlew assembleDebug
  artifacts:
    paths:
      - android/app/build/outputs/apk/debug/*.apk
    expire_in: 7 days
  needs: [test_unit, lint]
  except: [tags]

build_android_release:
  stage: build_android
  script:
    - cd android && ./gradlew assembleRelease
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    expire_in: 90 days
  needs: [test_unit, lint]
  only: [main, tags]
  environment:
    name: production/android

build_ios:
  stage: build_ios
  tags: [macos, xcode]
  script:
    - cd ios && pod install --repo-update
    - xcodebuild -workspace *.xcworkspace -scheme Release -sdk iphoneos -configuration Release archive
  artifacts:
    paths: [ios/build/]
    expire_in: 90 days
  needs: [test_unit, lint]
  only: [tags]
  allow_failure: true
  environment:
    name: production/ios

{_NOTIFICATION_JOB}
"""


# CI_TEMPLATES["flutter"] and CI_TEMPLATES["ionic"] have been removed in v2.1


def get_ci_template(framework: str | MobileFramework) -> str:
    """Get the CI/CD template for a given framework."""
    key = framework.value if isinstance(framework, MobileFramework) else framework
    return CI_TEMPLATES.get(key, CI_TEMPLATES["expo"])
