"""
GitLab Pusher Agent — pushes generated code to GitLab repositories.
Handles repo creation, branch management, and initial commit.
"""

from __future__ import annotations

import hashlib
import logging
import re
import json
import os
from typing import Any, Optional

from pipeline.core.config import config  # type: ignore
from pipeline.core.models import (  # type: ignore
    RepoManifest,
    MobileArchitecture,
    DesignBrief,
)
from pipeline.agents.ci_templates import get_ci_template  # type: ignore

logger = logging.getLogger("pipeline.pusher")


# ── GitLab Push ───────────────────────────────────────────────────────────

async def push_to_gitlab(
    manifest: RepoManifest,
    architecture: MobileArchitecture,
    files: dict[str, str],
    design_brief: Optional[DesignBrief] = None,
) -> str:
    """
    Push generated mobile app code to a new GitLab repository.
    
    Returns:
        GitLab repository URL.
    """
    idempotency_key = _build_push_idempotency_key(manifest, architecture, files)
    existing_url = _find_existing_push_for_key(idempotency_key)
    if existing_url:
        logger.info(f"Skipping duplicate push for {manifest.name}; using existing URL: {existing_url}")
        return existing_url

    try:
        import gitlab as gl_lib  # type: ignore
    except ImportError:
        logger.error("python-gitlab not installed — cannot push to GitLab")
        return ""

    token = config.gitlab.token
    url = config.gitlab.url
    namespace = config.gitlab.group

    if not token:
        logger.warning("GITLAB_TOKEN not set — skipping push")
        return ""

    try:
        gl = gl_lib.Gitlab(url, private_token=token)
        gl.auth()
    except Exception as e:
        logger.error(f"GitLab authentication failed: {e}")
        return ""

    # Build project name
    project_name = _build_project_name(manifest, architecture)

    try:
        # Create or get project
        project = _ensure_project(gl, namespace, project_name, manifest, architecture)

        # Add CI/CD template
        ci_template = get_ci_template(architecture.framework)
        files[".gitlab-ci.yml"] = ci_template

        # Commit all files
        _commit_files(project, files, manifest, architecture)

        # Set project settings
        _configure_project(project, manifest, architecture)

        repo_url = project.web_url
        logger.info(f"Pushed {len(files)} files to {repo_url}")
        
        # V2.5: Audit logging
        _write_audit_log(manifest, architecture, repo_url, idempotency_key=idempotency_key)
        
        return repo_url

    except Exception as e:
        logger.error(f"GitLab push failed for {manifest.name}: {e}")
        return ""


def _build_project_name(manifest: RepoManifest, arch: MobileArchitecture) -> str:
    """Build a clean GitLab project name."""
    # Format: {original-name}-mobile-{framework}
    base = re.sub(r"[^a-zA-Z0-9-]", "-", manifest.name.lower())
    base = re.sub(r"-+", "-", base).strip("-")
    fw = arch.framework.value.replace("_", "-")
    return f"{base}-mobile-{fw}"


def _ensure_project(gl, namespace: str, name: str, manifest: RepoManifest, arch: MobileArchitecture):
    """Create GitLab project or get existing one."""
    # Search for existing project
    try:
        projects = gl.projects.list(search=name, owned=True)
        for p in projects:
            if p.name == name:
                logger.info(f"Found existing project: {p.web_url}")
                return p
    except Exception:
        pass

    # Determine namespace ID
    namespace_id = None
    if namespace:
        try:
            groups = gl.groups.list(search=namespace)
            for g in groups:
                if g.full_path == namespace or g.name == namespace:
                    namespace_id = g.id
                    break
        except Exception:
            pass

    # Create new project
    project_data: dict[str, Any] = {
        "name": name,
        "description": (
            f"Mobile app ({arch.framework.value}) evolved from "
            f"{manifest.github_url} | "
            f"Generated by Repo Evolution Pipeline v2.0"
        ),
        "visibility": "private",
        "initialize_with_readme": False,
        "auto_devops_enabled": False,
        "shared_runners_enabled": True,
    }

    if namespace_id:
        project_data["namespace_id"] = namespace_id

    # Add topics/tags
    topics: list[str] = [
        "mobile",
        arch.framework.value,
        manifest.category.value,
        "repo-evolution",
        "auto-generated",
    ]
    project_data["topics"] = topics

    project = gl.projects.create(project_data)
    logger.info(f"Created new project: {project.web_url}")
    return project


def _commit_files(project, files: dict[str, str], manifest: RepoManifest, arch: MobileArchitecture):
    """Commit all generated files to the repository."""
    actions = []
    for path, content in files.items():
        action = {
            "action": "create",
            "file_path": path,
            "content": content,
        }
        # If it's a PNG, mark it as base64 encoded
        if path.endswith(".png"):
            action["encoding"] = "base64"
        
        actions.append(action)

    # Batch commit (GitLab API supports up to 200 actions per commit)
    batch_size = 150
    for i in range(0, len(actions), batch_size):
        batch = actions[i:i + batch_size]  # type: ignore
        batch_num = (i // batch_size) + 1
        total_batches = (len(actions) + batch_size - 1) // batch_size

        commit_msg = (
            f"feat: initial mobile app generation\n\n"
            f"Evolved from: {manifest.github_url}\n"
            f"Framework: {arch.framework.value}\n"
            f"Navigation: {arch.navigation_type.value}\n"
            f"State: {arch.state_management}\n"
            f"Screens: {len(arch.screens)}\n"
            f"Files: {len(files)}\n\n"
            f"Generated by Repo Evolution Pipeline v2.0"
        )

        if total_batches > 1:
            commit_msg = f"feat: generation batch {batch_num}/{total_batches}\n\n" + commit_msg

        try:
            project.commits.create({
                "branch": "main",
                "commit_message": commit_msg,
                "actions": batch,
            })
        except Exception as e:
            # If branch doesn't exist yet, try creating it
            if "branch" in str(e).lower() or "reference" in str(e).lower():
                try:
                    project.commits.create({
                        "branch": "main",
                        "start_branch": "main",
                        "commit_message": commit_msg,
                        "actions": batch,
                    })
                except Exception:
                    # Last resort: try default branch
                    project.commits.create({
                        "branch": project.default_branch or "main",
                        "commit_message": commit_msg,
                        "actions": batch,
                    })


def _configure_project(project, manifest: RepoManifest, arch: MobileArchitecture):
    """Configure project settings after creation."""
    try:
        # Set default branch
        project.default_branch = "main"

        # Add project avatar/description if needed
        project.description = (
            f"Mobile app ({arch.framework.value}) | "
            f"{len(arch.screens)} screens | "
            f"Evolved from {manifest.name}"
        )

        project.save()

        # Enable merge request approvals
        try:
            project.approvalrules.create({
                "name": "Default",
                "approvals_required": 1,
            })
        except Exception:
            pass  # May not be available on all GitLab tiers

        # Create development branch
        try:
            project.branches.create({
                "branch": "develop",
                "ref": "main",
            })
        except Exception:
            pass

    except Exception as e:
        logger.warning(f"Could not configure project settings: {e}")


def _build_push_idempotency_key(
    manifest: RepoManifest,
    arch: MobileArchitecture,
    files: dict[str, str],
) -> str:
    """Build a deterministic idempotency key for push side effects."""
    hasher = hashlib.sha256()
    hasher.update(manifest.name.encode("utf-8"))
    hasher.update(manifest.github_url.encode("utf-8"))
    hasher.update((manifest.commit_sha or "").encode("utf-8"))
    hasher.update(arch.framework.value.encode("utf-8"))
    hasher.update(arch.navigation_type.value.encode("utf-8"))

    # Include generated content shape and hash for deterministic rerun detection.
    for path in sorted(files.keys()):
        content = files[path]
        content_hash = hashlib.sha256(content.encode("utf-8", errors="ignore")).hexdigest()
        hasher.update(path.encode("utf-8"))
        hasher.update(content_hash.encode("utf-8"))

    return hasher.hexdigest()[:24]  # type: ignore


def _find_existing_push_for_key(idempotency_key: str) -> str:
    """Return existing GitLab URL for an idempotent push if present in audit log."""
    log_path = os.path.join(config.data_dir, "logs", "push_audit.jsonl")
    if not os.path.exists(log_path):
        return ""

    try:
        with open(log_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
    except Exception:
        return ""

    for raw in reversed(lines):
        try:
            entry = json.loads(raw)
        except Exception:
            continue

        if entry.get("idempotency_key") != idempotency_key:
            continue

        destination = entry.get("gitlab_destination", "")
        if isinstance(destination, str) and destination:
            return destination

    return ""


def _write_audit_log(manifest: RepoManifest, arch: MobileArchitecture, url: str, *, idempotency_key: str):
    """Write a machine-readable audit log for the push event."""
    from datetime import datetime
    
    log_dir = os.path.join(config.data_dir, "logs")
    os.makedirs(log_dir, exist_ok=True)
    
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "event": "project_push",
        "idempotency_key": idempotency_key,
        "repo": manifest.name,
        "github_source": manifest.github_url,
        "gitlab_destination": url,
        "framework": arch.framework.value,
        "screens": len(arch.screens),
    }
    
    log_path = os.path.join(log_dir, "push_audit.jsonl")
    with open(log_path, "a") as f:
        f.write(json.dumps(log_entry) + "\n")


# ── Utilities ─────────────────────────────────────────────────────────────

def validate_gitlab_connection() -> bool:
    """Test GitLab connectivity."""
    try:
        import gitlab as gl_lib  # type: ignore
        gl = gl_lib.Gitlab(config.gitlab.url, private_token=config.gitlab.token)
        gl.auth()
        logger.info(f"GitLab connected as {gl.user.username}")
        return True
    except Exception as e:
        logger.error(f"GitLab connection failed: {e}")
        return False
